### ISSUE TITLE
Wrong voucher value in oder notification mail on different currencies

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#234]
**Describe the bug**
If you use an voucher within an order and use other currency than the base currency. The cms saves the original voucher value and not the currency converted value to the order. So on the order notification email we display the wrong used voucher value.  

**Affected version(s)**
6.2

**To Reproduce**
1.Make an order with a voucher and other currecny than the default
2. In cms go to the order to field "Used vouchers" onyl the base currency value was saved
3. Wrong voucher values in the order notification
4. Wrong currency and values in order history in my account

**Expected behavior**
In the order notification we should display the corret used voucher value in the use currency during order.

**Technical details**
The old field with the base currency value should be kept. Because we use this vlaue to make some calculations. We should add a new field and save the used currency value there.
So we can use this to display the voucher value.

**Comment by esono-anja** [comment]
There is still the wrong value displayed in the order notification as well as in the order history (even though the total is calcualated right).
![voucher_value](https://user-images.githubusercontent.com/15125103/50910290-ca33ff80-142d-11e9-8fe9-30fbd993df98.png)

**Comment by pixeljunkie** [comment]
Isn't this only the name of the voucher? I think this is o.k.

**Comment by esono-anja** [comment]
left is the name of the voucher, but right is the actual voucher value

**Comment by umulmrum** [comment]
@pSpeck Could you have a look?

**Comment by umulmrum** [comment]
The fix was merged into master instead of 6.2.x - I cherry-picked it now, please retry.

**Comment by esono-anja** [comment]
The error still occurs.
There is the following error notification above the order history:
Notice: Undefined property: TdbShopVoucherUse::$fieldValueUsedInOrderCurrency in /usr/local/apache2/htdocs/releases/2019-01-10-11-48-50/customer/vendor/chameleon-system/chameleon-shop/src/ShopBundle/mappers/order/TPkgShopMapper_OrderArticleListSummary.class.php on line 183

Notice: Undefined property: TdbShopVoucherUse::$fieldValueUsedInOrderCurrency in /usr/local/apache2/htdocs/releases/2019-01-10-11-48-50/customer/vendor/chameleon-system/chameleon-shop/src/ShopBundle/mappers/order/TPkgShopMapper_OrderArticleListSummary.class.php on line 185

**Comment by pSpeck** [comment]
Sorry I forgot to add an update

**Comment by esono-anja** [comment]
The problem still occurs (except for the error notification above the order history , which is gone now).

**Comment by umulmrum** [comment]
Hard piece of work :-) - thanks @esono-anja @pSpeck !
